### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by gdeflaux**

### CODE REVIEW

**Comment by gdeflaux** [comment]
The interact page is only a partial translation since some of the content can be translated into different languages.

**Comment by moritzheiber** [comment]
Can or can't?

**Comment by gdeflaux** [comment]
Can't. They are outside one of the locale folders (en, fr, hu, ...).

**Comment by moritzheiber** [comment]
Ah, do you have an example?

**Comment by gdeflaux** [comment]
This comment is specifically for the interact page located in `content/fr/interact/_index.md`. The layout associated with this page located in `layouts/interact/list.html` has English text in it and includes another partial from the theme itself `themes/docsy/layouts/partials/community_links.html`.

We could move the content of the layout directly into the localized file but it doesn't solve the problem of the theme partial. I don't know how to localize the theme files.

Hope it's clearer this time :)

**Comment by moritzheiber** [comment]
I've added #24 to try to solve this .. once it's merged, could you do another round-trip and translate the rest of the string?

**Comment by kgilmer** [comment]
Thanks for making the change to add support for partials @moritzheiber .  We can also just get rid of t hem for the Interact page.  They don't look particularly great.  I'm a little better with Bootstrap now and have a better feel for page layout in general.

**Comment by kgilmer** [comment]
Thank you @gdeflaux !

**Comment by kgilmer** [comment]
> I've added #24 to try to solve this .. once it's merged, could you do another round-trip and translate the rest of the strings?

This PR is merged and published (FYI)

**Pull request merged**
