### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by matiasnoriega**
Started a spanish translation of the website and documentation as requested on regolith-linux/regolith-desktop#127 . I'll keep advancing in the documentation translation.

### CODE REVIEW

**Comment by kgilmer** [comment]
Fantastic, thank you @matiasnoriega !  Let me know when you'd like me to merge this.  We can do all at once or incremental, it's your choice.

**Comment by matiasnoriega** [comment]
Let's do it in an incremental way, so if you want to merge the translation so far, is good to me :D

**Comment by kgilmer** [comment]
Will do @matiasnoriega !  :smile:

**Comment by kgilmer** [comment]
It's live!  https://regolith-linux.org/es/

You'll probably want to rebase.

**Pull request merged**
