### PR TITLE
Removed submodule in favor of sub-tree pushing

### PR DESCRIPTION
**Pull request by moritzheiber**
This removes the submodule (which always required an extra commit to pin the tip) in favor of a sub-tree push on the `/public` folder. The added benefit is a common commit history across repositories instead of diverging histories (makes reverting commits a lot easier), with the downside of keeping the rendered website in Git twice.

### CODE REVIEW

**Comment by kgilmer** [comment]
Interesting, I didn't know there was such a thing as sub-tree pushing in git.  I'm guessing I can test this locally by pulling your branch, making a change, and deploying to prod?

**Comment by moritzheiber** [comment]
You’ll need to remove the submodule as well before that. And you’ll probably need to force push to the website Git repository, since right now it’s tracking a different history. You could try pushing into an empty repository first (just change the URL)

**Comment by moritzheiber** [comment]
If it helps, it’s how I’m pushing my own Hugo blog 😉

**Comment by kgilmer** [comment]
And a fine blog it is!

**Comment by kgilmer** [comment]
Ok so I tried to test.  This is what I did:
1. Checkout your repo and use remove_submodule branch
2. update deploy script to not push to origin (line 23) since I cannot do that
3. Create a test public repo https://github.com/regolith-linux/website-test
4. Set GIT_URL to said test repo, run scipt.
5. Observe files being published to test repo.  Compare with other site repos, looks good.
6. Enable gh-pages in the settings of test repo

It should be published to this URL: http://regolith-linux.org/website-test/

However I'm getting a 404.  Not sure what could be wrong.  The docs say it can take "up to 20 minutes".  I've waited that long and still no dice.  Will leave it overnight and see if it starts working.

**Comment by kgilmer** [comment]
It works w/ HTTPS so looks like we are GTG.

**Comment by moritzheiber** [comment]
Will do. Glad it worked out.

**Pull request merged**
