### PR TITLE
added content on changing the display manager's wallpaper

### PR DESCRIPTION
**Pull request by Vruttant**
Added content in the regolith docs on how to change the default login manager's (lightdm) wallpaper in reference to the issue [regolith-linux/website#22](https://github.com/regolith-linux/website/issues/22)

### CODE REVIEW

**Comment by moritzheiber** [comment]
No, sorry, one should never edit the system's supplied configuration, but rather provide your own override. That's what the `/etc/lightdm/lightdm.conf.d/` is for. If you adjust your PR accordingly I'll consider merging it, but we don't tell users to modify system configuration files.

**Comment by Vruttant** [comment]
> No, sorry, one should never edit the system's supplied configuration, but rather provide your own override. That's what the `/etc/lightdm/lightdm.conf.d/` directory is for. If you adjust your PR accordingly I'll consider merging it, but we don't tell users to modify system configuration files.

@moritzheiber My bad i will try to fix this as soon as possible.

**Comment by Vruttant** [comment]
@moritzheiber I looked around for a while and i was thinking if the system config file for lightdm is located in `/usr/share/lightdm/lightdm-gtk-greeter.conf.d` with file names `01_ubuntu.conf` and `02_regolith.conf`? I couldn't find any conf file in my `/etc/lightdm/lightdm.conf.d/`. 
Ref: [LightDM](https://wiki.ubuntu.com/LightDM)

**Comment by moritzheiber** [comment]
Yes, you will have to create your own file in order to utilize this functionality (as the documentation tells you to).

**Comment by Vruttant** [comment]
I tried making a conf file in my `/etc/lightdm/lightdm.conf.d/` with the name `50-myconfig.conf` with following content
```
[SeatDefaults]
user-session=mysession

[greeter]
background=/home/vruttant/Downloads/Wallpapers/simple_log.png
```
but this didn't changed the background, so i tried the GUI option (`lightdm-gtk-greeter-settings`) and noticed that it also edits the `/etc/lightdm/lightdm-gtk-greeter.conf` and in [LightDM](https://wiki.ubuntu.com/LightDM) wiki it says for changing wallpaper you need to edit the **lightdm-gtk-greeter** config file.

Please let me know if this issue is only with me.

**Comment by moritzheiber** [comment]
LightDM runs under its own user which needs to have access to whatever wallpaper you want to have it displayed. Since you're referencing your home directory, which, by default, only your own user should have access to, LightDM will likely fail to adopt your custom settings and use the value(s) it received before processing your configuration file.

Try moving the wallpaper into a more public place (LightDM's documentation recommends `/usr/share/backgrounds`) or switching to a wallpaper that's already present in `/usr/share` somewhere (e.g. `/usr/share/backgrounds/warty-final-ubuntu.png`).

Aside from that I just learned that `lightdm-gtk-greeter` now actually has its own `conf.d` directory (which is, as you already mentioned, `/usr/share/lightdm/lightdm-gtk-greeter.conf.d`) and it only adopts the settings when I put the added user configuration in that particular directory instead of the `lightdm.conf.d`. Figures .. so `/usr/share/lightdm/lightdm-gtk-greeter.conf.d` is the place for the configuration to go into I reckon.

Sidenote: You can take a look at `/var/log/lightdm/seat0-greeter.log` to diagnose any issues *and* you have to restart LightDM (`systemctl restart lightdm`) when changing these settings it would appear.

**Comment by kgilmer** [comment]
Assuming this PR is no longer needed.  Kindly reopen if I'm mistaken.

**Pull request closed without merging**
